/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const Meta = t.iface([], {
  "imageProcessing": t.opt(t.iface([], {
    "enabled": "boolean",
    "quality": t.opt("number"),
    "imageType": t.opt(t.union(t.lit('original'), t.lit('auto'))),
  })),
  "cache": t.opt(t.iface([], {
    "headers": "boolean",
  })),
  "security": t.opt(t.iface([], {
    "csp": t.opt("string"),
    "standardHeaders": t.opt("boolean"),
    "hideVersion": t.opt("boolean"),
  })),
  "removeTrailingSlash": t.opt("boolean"),
  "redirects": t.opt(t.array("Redirect")),
  "multisite": t.opt(t.iface([], {
    "enabled": "boolean",
    "sites": t.opt(t.array("Site")),
  })),
});

const exportedTypeSuite: t.ITypeSuite = {
  Meta,
};
export default exportedTypeSuite;
