/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const Redirect = t.iface([], {
  from: 'string',
  to: 'string',
  regex: t.opt('boolean'),
  code: t.opt(
    t.union(
      t.lit('301'),
      t.lit('302'),
      t.lit('307'),
      t.lit(301),
      t.lit(302),
      t.lit(307),
    ),
  ),
  site: t.opt('string'),
});

const exportedTypeSuite: t.ITypeSuite = {
  Redirect,
};
export default exportedTypeSuite;
