version: '2.4'
services:
  queue:
    image: nats:2.1.9-scratch
    hostname: queue
    ports:
      - 4222:4222
      - 8222:8222
  webserver:
    image: openresty/openresty:1.19.3.1-buster
    ports:
      - 8081:8081
      - 8082:8082
    user: www-data
    volumes:
      - nginx:/home/papergirl/nginx
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro,delegated
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,delegated
  s3:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
    volumes:
      - ./s3-data:/data
  app:
    build:
      context: .
      target: development
    environment:
      CONFIG: docker-compose
    ports:
      - 8080:8080
    depends_on:
      - queue
      - webserver
    pid: service:webserver
    volumes:
      - ./src:/home/papergirl/app/src:ro,delegated
      - ./config:/home/papergirl/app/config:ro,delegated
      - nginx:/home/papergirl/nginx
volumes:
  nginx: null
