version: "2.4"
services:
  queue:
    image: nats:2.1.2-scratch
    hostname: queue
    ports:
    - 4222:4222
    - 8222:8222
  webserver:
    image: nginx:1.17.8
    ports:
    - 8081:8081
    - 8082:8082
    user: nginx
    volumes:
    - nginx:/home/papergirl/nginx
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
  s3:
    image: minio/minio:RELEASE.2020-01-25T02-50-51Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
    - 9000:9000
    volumes:
    - ./s3-data:/data
  app:
    build:
      context: .
      target: development
    environment:
      CONFIG: docker-compose
    ports:
    - 8080:8080
    depends_on:
    - queue
    - webserver
    pid: service:webserver
    volumes:
    - ./src:/home/papergirl/app/src:ro,consistent
    - nginx:/home/papergirl/nginx
volumes:
  nginx: null
