# Disable default pod anti affinity rule to schedule multiple replicas in a single node cluster
affinity:
  podAntiAffinity: {}

# Enable Caravaggio
imageProxy:
  enabled: true

# Use locally build Papergirl image
image:
  repository: localhost:5000/papergirl
  tag: latest
  pullPolicy: Always

# Increase memory limit to allow for live reloading / dev mode
resources:
  limits:
    memory: 512Mi

# Enable development mode
develop: true

nats:
  url: nats://nats.nats:4222
