{{- if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "papergirl.fullname" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  groups:
    - name: nginx-alerts
      rules:
        - alert: NginxInstanceIsDown
          expr: |
            nginx_up{namespace="cms"} == 0
          for: 30m
          labels:
            severity: warning
          annotations:
            description: NGINX server of pod \{\{\$labels.pod\}\} has been down for 30 minutes.
{{- end }}