apiVersion: v1
kind: Service
metadata:
  name: {{ include "papergirl.fullname" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "papergirl.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
