kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "papergirl.fullname" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["*"]