apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papergirl.fullname" . }}-config
data:
  kubernetes.env: |
    {{- $data := dict "s3BucketName" .Values.s3.buckets.name "s3Endpoint" (include "papergirl.s3.endpoint" .) "s3" .Values.s3 "name" (include "papergirl.fullname" .) "queueUri" (include "papergirl.nats.url" .)  "queueSubject" "papergirl" "Template" .Template -}}
    {{- tpl (.Files.Get "papergirl.env") $data | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papergirl.fullname" . }}-nginx-config
data:
  nginx.conf: |
{{- (.Files.Get "nginx.conf") | nindent 4 }}