apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papergirl.backup.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
data:
  backup.sh: |
    {{- tpl (.Files.Get "backup.sh") . | nindent 4 }}