apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "papergirl.fallback.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.backup.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
        app.kubernetes.io/name: {{ include "papergirl.fallback.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        papergirl/fallback-config-hash: {{ tpl (.Files.Get "nginx.conf.template") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "papergirl.fallback.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets: 
      - name: {{ include "papergirl.pull-secret-name" . }}
      {{- end }}
      containers:
      - name: nginx
        image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
        imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
        env:
          - name: BUCKET_NAME
            value: {{ include "papergirl.backup.name" . }}
        ports:
          - containerPort: 80
            name: http
        args:
          - /bin/bash
          - -c
          - "envsubst < /nginx-config/nginx.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        volumeMounts:
        - name: nginx-config-template
          mountPath: /nginx-config
      volumes:
        - name: nginx-config-template
          configMap:
            name: {{ include "papergirl.fallback.name" . }}