{{- if .Values.minio.createCluster -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "papergirl.minio.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "papergirl.minio.name" . }}
{{- end -}}