{{- if and .Values.minio.createCluster (ge (int .Values.minio.version) 4) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "papergirl.minio.name" . }}-console-credentials
  labels:
{{ include "papergirl.labels" . | indent 4 }}
type: Opaque
data:
  CONSOLE_PBKDF_PASSPHRASE: {{ .Values.minio.console.pbkdfPassphrase | b64enc }}
  CONSOLE_PBKDF_SALT: {{ .Values.minio.console.pbkdfSalt | b64enc }}
  CONSOLE_ACCESS_KEY: {{ .Values.minio.console.accesskey | b64enc }}
  CONSOLE_SECRET_KEY: {{ .Values.minio.console.secretkey | b64enc }}
{{- end -}}