{{- if .Values.minio.createCluster -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "papergirl.minio.name" . }}-credentials
  labels:
{{ include "papergirl.labels" . | indent 4 }}
type: Opaque
data:
  accesskey: {{ .Values.s3.accesskey | b64enc }}
  secretkey: {{ .Values.s3.secretkey | b64enc }}
{{- end -}}