{{- if and .Values.minio.createCluster (ge (int .Values.minio.version) 4) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "papergirl.minio.name" . }}-console
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    v1.min.io/console: {{ include "papergirl.minio.name" . }}-console
{{- end -}}
