{{- if .Values.minio.createCluster -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "papergirl.minio.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  {{- if .Values.develop }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      {{- if .Values.develop }}
      nodePort: 30003
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "papergirl.minio.name" . }}
{{- end -}}