{{- if .Values.nats.enabled -}}
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: {{ include "papergirl.nats.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  size: {{ .Values.nats.size }}
  version: "{{ .Values.nats.version }}"
{{- end }}