{{- if .Values.papergirlPreview.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "papergirl.preview.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "papergirl.preview.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}