kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "papergirl.preview.name" . }}
  labels:
{{ include "papergirl.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "papergirl.preview.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "papergirl.preview.name" . }}