{{- if .Values.papergirlPreview.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papergirl.preview.name" . }}-config
data:
  kubernetes.env: |
    {{- $data := dict "s3BucketName" .Values.s3.buckets.previewName "s3Endpoint" (include "papergirl.s3.endpoint" .) "s3" .Values.s3 "name" (include "papergirl.preview.name" .) "queueUri" (include "papergirl.nats.url" .) "queueSubject" "papergirl-preview" "Template" .Template -}}
    {{- tpl (.Files.Get "papergirl.env") $data | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "papergirl.preview.name" . }}-nginx-config
data:
  nginx.conf: |
{{- (.Files.Get "nginx.conf") | nindent 4 }}
{{- end }}