replicaCount: 2

websiteCache:
  storageClass: ""
  size: 1Gi

volumeSetup:
  image:
    repository: busybox
    tag: 1.31.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: 
    limits:
      cpu: 50m
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi

nginx:
  image:
    repository: nginx
    tag: 1.17.6
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

papergirl:
  image:
    repository: neoskop/papergirl
    tag: 0.0.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: 
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

minio:
  enabled: true
  accesskey: minio
  secretkey: minio123
  storageClass: ""
  replicaCount: 4
  image:
    repository: minio/minio
    tag: RELEASE.2019-09-11T19-53-16Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: 
    limits:
      memory: 512Mi
      cpu: 250m
    requests:
      memory: 512Mi
      cpu: 250m

nats:
  enabled: true
  size: 3
  version: 2.1.2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}
