develop: false
image:
  repository: neoskop/papergirl
  tag: 1.4.1
  pullPolicy: IfNotPresent
websiteCache:
  storageClass: ''
  size: 1Gi
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 150m
    memory: 128Mi
replicaCount: 2
connectionCheck:
  image:
    repository: busybox
    tag: 1.33.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
bucketSetup:
  image:
    repository: minio/mc
    tag: RELEASE.2021-06-13T17-48-22Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
volumeSetup:
  image:
    repository: busybox
    tag: 1.33.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
dnsmasq:
  image:
    repository: janeczku/go-dnsmasq
    tag: release-1.0.7
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 5m
      memory: 25Mi
nginx:
  image:
    repository: openresty/openresty
    tag: 1.19.3.2-buster
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
prometheus:
  enabled: false
  nginxExporterImage:
    repository: nginx/nginx-prometheus-exporter
    tag: 0.9.0
    pullPolicy: IfNotPresent
    pullSecrets: []
papergirl:
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
papergirlPreview:
  enabled: true
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
minio:
  createCluster: true
  version: 4
  endpoint: null
  accesskey: minio
  secretkey: minio123
  storageClass: ''
  storageSize: 5Gi
  replicaCount: 4
  volumesPerReplica: 1
  console:
    pbkdfPassphrase: secret
    pbkdfSalt: secret
    accesskey: admin
    secretkey: minio456
    image:
      repository: minio/console
      tag: v0.7.5
      pullPolicy: IfNotPresent
      pullSecrets: []
  image:
    repository: minio/minio
    tag: RELEASE.2021-07-08T01-15-01Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
backup:
  schedule: '0 5 * * *'
  image:
    repository: minio/mc
    tag: RELEASE.2021-06-13T17-48-22Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
imageProxy:
  enabled: false
  image:
    repository: ramielcreations/caravaggio
    tag: 3.5.0
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
  args:
    - --cache none
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.3.2
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
nodeSelector: {}
tolerations: []
affinity: {}
