develop: false
image:
  repository: neoskop/papergirl
  tag: 1.12.2
  pullPolicy: IfNotPresent
websiteCache:
  storageClass: ''
  size: 1Gi
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 150m
    memory: 128Mi
replicaCount: 2
connectionCheck:
  image:
    repository: busybox
    tag: 1.34.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
volumeSetup:
  image:
    repository: busybox
    tag: 1.34.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
dnsmasq:
  image:
    repository: janeczku/go-dnsmasq
    tag: release-1.0.7
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 50Mi
    requests:
      cpu: 5m
      memory: 25Mi
nginx:
  image:
    repository: openresty/openresty
    tag: 1.19.9.1-buster
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
prometheus:
  enabled: false
  nginxExporterImage:
    repository: nginx/nginx-prometheus-exporter
    tag: 0.9.0
    pullPolicy: IfNotPresent
papergirl:
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
papergirlPreview:
  enabled: true
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
s3:
  endpoint: null
  port: 9000
  ssl: false
  accesskey: minio
  secretkey: minio123
  buckets:
    name: papergirl
    backupName: papergirl-backup
    previewName: papergirl-preview
    previewBackupName: papergirl-preview-backup
minio:
  createCluster: true
  version: 4
  storageClass: ''
  storageSize: 5Gi
  replicaCount: 4
  volumesPerReplica: 1
  console:
    pbkdfPassphrase: secret
    pbkdfSalt: secret
    accesskey: admin
    secretkey: minio456
    image:
      repository: minio/console
      tag: v0.9.8
      pullPolicy: IfNotPresent
  image:
    repository: minio/minio
    tag: RELEASE.2021-09-09T21-37-07Z
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
backup:
  schedule: '0 5 * * *'
  image:
    repository: minio/mc
    tag: RELEASE.2021-09-02T09-21-27Z
    pullPolicy: IfNotPresent
  replicaCount: 2
imageProxy:
  enabled: false
  image:
    repository: ramielcreations/caravaggio
    tag: 3.6.1
    pullPolicy: IfNotPresent
  replicaCount: 2
  args:
    - --cache none
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.5.0
imagePullSecret: {}
nameOverride: ''
fullnameOverride: ''
nodeSelector: {}
tolerations: []
affinity: {}
