replicaCount: 2
websiteCache:
  storageClass: ""
  size: 1Gi
volumeSetup:
  image:
    repository: busybox
    tag: 1.31.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 50m
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
nginx:
  image:
    repository: nginx
    tag: 1.17.8
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
prometheus:
  enabled: false
  nginxExporterImage:
    repository: nginx/nginx-prometheus-exporter
    tag: 0.5.0
    pullPolicy: IfNotPresent
    pullSecrets: []
papergirl:
  image:
    repository: neoskop/papergirl
    tag: 0.1.3
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
minio:
  createCluster: true
  endpoint: null
  accesskey: minio
  secretkey: minio123
  storageClass: ""
  replicaCount: 4
  image:
    repository: minio/minio
    tag: RELEASE.2020-01-25T02-50-51Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 512Mi
      cpu: 250m
    requests:
      memory: 512Mi
      cpu: 250m
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.1.2
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}
tolerations: []
affinity: {}
