image:
  repository: neoskop/papergirl
  tag: 1.0.0
  pullPolicy: IfNotPresent
websiteCache:
  storageClass: ''
  size: 1Gi
resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 150m
    memory: 128Mi
replicaCount: 2
connectionCheck:
  image:
    repository: busybox
    tag: 1.33.0
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
bucketSetup:
  image:
    repository: minio/mc
    tag: RELEASE.2021-03-23T05-46-11Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
volumeSetup:
  image:
    repository: busybox
    tag: 1.33.0
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 16Mi
    requests:
      cpu: 50m
      memory: 16Mi
nginx:
  image:
    repository: openresty/openresty
    tag: 1.19.3.1-buster
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
prometheus:
  enabled: false
  nginxExporterImage:
    repository: nginx/nginx-prometheus-exporter
    tag: 0.9.0
    pullPolicy: IfNotPresent
    pullSecrets: []
papergirl:
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
papergirlPreview:
  enabled: true
  ingress:
    enabled: false
    hostnames:
      - papergirl.local
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
minio:
  createCluster: true
  version: 4
  endpoint: null
  accesskey: minio
  secretkey: minio123
  storageClass: ''
  storageSize: 5Gi
  replicaCount: 4
  console:
    pbkdfPassphrase: secret
    pbkdfSalt: secret
    accesskey: admin
    secretkey: minio456
    image:
      repository: minio/console
      tag: v0.6.6
      pullPolicy: IfNotPresent
      pullSecrets: []
  image:
    repository: minio/minio
    tag: RELEASE.2021-04-06T23-11-00Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
backup:
  schedule: '0 5 * * *'
  image:
    repository: minio/mc
    tag: RELEASE.2021-03-23T05-46-11Z
    pullPolicy: IfNotPresent
    pullSecrets: []
  replicaCount: 2
nats:
  createCluster: true
  url: null
  size: 3
  version: 2.2.1
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
nodeSelector: {}
tolerations: []
affinity: {}
